AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for sam-ml-predict

Globals:
  Function:
    Timeout: 3

Resources:
  MLSamFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /predict
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./app
      DockerTag: python3.8-v1

Outputs:
  MLSamFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for ML Sam Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/predict/"
  MLSamFunction:
    Description: "ML Sam Function Predict Lambda Function ARN"
    Value: !GetAtt MLSamFunction.Arn
  MLSamFunctionIamRole:
    Description: "Implicit IAM Role created for ML Sam Function"
    Value: !GetAtt MLSamFunctionRole.Arn
